services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    labels:
      de.danielr1996.bashdoard.name: Vaultwarden
      de.danielr1996.bashdoard.url: https://vault.local.app.danielr1996.de
      de.danielr1996.bashdoard.icon: /images/favicon-16x16.png
      de.danielr1996.bashdoard.id: vaultwarden
      traefik.enable: true
      traefik.http.routers.vault.rule: Host(`vault.local.app.danielr1996.de`)
      traefik.http.routers.vault.tls.certresolver: letsencrypt
      traefik.http.routers.vault.service: vault
      traefik.http.services.vault.loadbalancer.server.port: 80

      traefik.http.routers.vaultws.rule: Host(`vault.local.app..danielr1996.de`) && Path(`/notifications/hub`)
      traefik.http.routers.vaultws.service: vaultws
      traefik.http.routers.vaultws.tls.certresolver: letsencrypt
      traefik.http.services.vaultws.loadbalancer.server.port: 3012
    volumes:
      - /data/vaultwarden/config:/data
    environment:
      WEBSOCKET_ENABLED: true
      DATABASE_URL: "postgresql://vaultwarden:vaultwarden@db/vaultwarden"
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: vaultwarden
      POSTGRES_USER: vaultwarden
      POSTGRES_DB: vaultwarden
    volumes:
      - /data/vaultwarden/db:/var/lib/postgresql/data